apiVersion: v1
kind: Service
metadata:
  name: mlops-api-service
spec:
  selector:
    app: mlops-api
  ports:
    - name: metrics          # 👈 NOMBRE DEL PUERTO EXPUESTO
      protocol: TCP
      port: 5000             # puerto interno del servicio
      targetPort: 5000       # puerto del contenedor
  type: ClusterIP            # SOLO interno al clúster
