FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src

EXPOSE 8501
# Dirección 0.0.0.0 para servir fuera del contenedor y puerto fijo
CMD ["streamlit", "run", "src/iris/app_web.py", "--server.port=8501", "--server.address=0.0.0.0"]
