# Imagen base ligera
FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1
WORKDIR /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar código y artefactos necesarios para inferencia
COPY app_telco.py .
COPY model_telco.pkl .
COPY artifacts_telco ./artifacts_telco

# Puerto de la API Telco
EXPOSE 5001

# Lanzar la API Telco
CMD ["python", "app_telco.py"]
