stages:
  prepare:
    cmd: echo "Verificando que los datos existen..."
    deps:
      - data/iris_dataset.csv

  train:
    cmd: python src/iris/train.py --n_estimators ${train.n_estimators}
    deps:
      - src/iris/train.py
      - requirements.txt
      - data/iris_dataset.csv
    outs:
      - model.pkl
      - confusion_matrix.png
    metrics:
      - mlflow_metrics.json
    params:
      - train.n_estimators

  prepare_telco:
    cmd: echo "Verificando que el dataset Telco existe..."
    deps:
      - data/telco_churn.csv

  train_telco:
    cmd: python src/telco_xai/train_telco.py
    deps:
      - src/telco_xai/train_telco.py
      - requirements.txt
      - data/telco_churn.csv
    outs:
      - model_telco.pkl
    metrics:
      - telco_metrics.json
