apiVersion: v1
kind: Service
metadata:
  name: mlops-api-service
spec:
  selector:
    app: mlops-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80        # puerto público (externo)
      targetPort: 5000  # puerto del contenedor
